name: tt
channels:
  - Microsoft
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2024.07.04
  - libffi=3.4.4
  - openssl=3.3.1
  - python=3.11.9
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.3.1
  - pip
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.10.2
    - aiosignal==1.3.1
    - anyio==4.4.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==24.2.0
    - babel==2.15.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - cachetools==5.4.0
    - certifi==2024.7.4
    - cffi==1.17.0
    - charset-normalizer==3.3.2
    - cloudpickle==3.0.0
    - cmake==3.30.2
    - comm==0.2.2
    - debugpy==1.8.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dm-tree==0.1.8
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - executing==2.0.1
    - fastjsonschema==2.20.0
    - filelock==3.15.4
    - flatbuffers==24.3.25
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.6.1
    - gast==0.6.0
    - google-auth==2.32.0
    - google-auth-oauthlib==1.2.1
    - google-pasta==0.2.0
    - grpcio==1.65.4
    - h5py==3.11.0
    - idna==3.7
    - ipykernel==6.29.5
    - ipython==8.26.0
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - kaleido==0.2.1
    - keras==3.6.0
    - libclang==18.1.1
    - lightning-bolts==0.7.0
    - lightning-utilities==0.11.6
    - lit==18.1.8
    - markdown==3.6
    - markupsafe==2.1.5
    - matplotlib==3.9.1
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - monai==1.3.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.3
    - notebook-shim==0.2.4
    - nptyping==2.5.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - onnx==1.16.2
    - onnx-tf==1.10.0
    - opencv-python==4.10.0.84
    - opt-einsum==3.3.0
    - overrides==7.7.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pip==24.2
    - platformdirs==4.2.2
    - plotly==5.22.0
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.47
    - protobuf==5.27.3
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pygments==2.18.0
    - pynrrd==1.0.0
    - python-json-logger==2.0.7
    - pytorch-lightning==2.4.0
    - pytz==2024.1
    - pyyaml==6.0.2
    - pyzmq==26.1.0
    - referencing==0.35.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.20.0
    - rsa==4.9
    - scikit-learn==1.5.1
    - scipy==1.13.1
    - send2trash==1.8.3
    - setuptools==72.1.0
    - simpleitk==2.4.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - sympy==1.13.2
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.18.0
    - tensorflow-addons==0.23.0
    - tensorflow-estimator==2.18.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorflow-probability==0.25.0
    - termcolor==2.4.0
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - tinycss2==1.3.0
    - tomli==2.0.1
    - torch==2.4.0
    - torchaudio==2.4.0
    - torchvision==0.19.0
    - tornado==6.4.1
    - tqdm==4.66.5
    - traitlets==5.14.3
    - triton==3.0.0
    - ttach==0.0.3
    - typeguard==4.3.0
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.2
    - wcwidth==0.2.13
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.0.3
    - wheel==0.44.0
    - wrapt==1.16.0
    - yarl==1.9.4
    - zlib==1.2.2